language: 'node_js'
node_js: 
  - '12'

install:
 - npm install

script:
 - ./node_modules/.bin/jshint src/
 - ./node_modules/.bin/retire
 - if [ "$TRAVIS_BRANCH" = "master" ]; then./node_modules/.bin/twly; fi
